pub fn get_macos_excludes() -> Vec<String> {
    vec![
        "./**/*.sock".to_string(),
        "./**/.venv".to_string(),
        "./**/__worktrees".to_string(),
        "./**/node_modules".to_string(),
        "./**/target".to_string(),
        "./.Trash".to_string(),
        "./.cache/huggingface".to_string(),
        "./.cache/nix".to_string(),
        "./.cargo".to_string(),
        "./.cursor/extensions".to_string(),
        "./.gnupg/S.*".to_string(),
        "./.local/share/nvim".to_string(),
        "./.npm".to_string(),
        "./.ollama/models".to_string(),
        "./.orbstack".to_string(),
        "./.pulumi".to_string(),
        "./.terraform.d".to_string(),
        "./.vscode/extensions".to_string(),
        "./Library/Application Support/Chromium".to_string(),
        "./Library/Application Support/Cursor".to_string(),
        "./Library/Application Support/FileProvider".to_string(),
        "./Library/Application Support/Firefox".to_string(),
        "./Library/Application Support/Google".to_string(),
        "./Library/Application Support/Slack".to_string(),
        "./Library/Application Support/rancher-desktop".to_string(),
        "./Library/Caches".to_string(),
        "./Library/Caches/CloudKit".to_string(),
        "./Library/Caches/FamilyCircle".to_string(),
        "./Library/Caches/Firefox".to_string(),
        "./Library/Caches/com.anthropic.claudefordesktop.ShipIt".to_string(),
        "./Library/Caches/com.apple.HomeKit".to_string(),
        "./Library/Caches/com.apple.Safari".to_string(),
        "./Library/Caches/com.apple.ap.adprivacyd".to_string(),
        "./Library/Caches/com.apple.containermanagerd".to_string(),
        "./Library/Caches/com.apple.homed".to_string(),
        "./Library/Caches/pypoetry".to_string(),
        "./Library/Containers".to_string(),
        "./Library/Developer/Xcode".to_string(),
        "./Library/Group Containers".to_string(),
        "./Library/Mobile Documents/com~apple~CloudDocs".to_string(),
        "./OrbStack".to_string(),
        "./Pictures".to_string(),
        "./Sources/github.com/NixOS/nixpkgs".to_string(),
        "./go".to_string(),
    ]
}
